huggingface:
  model: "mistralai/Mistral-7B-Instruct-v0.2"
  revision: "41b61a33a2483885c981aa79e0df6b32407ed873"
  download: true
djl:
  engine: "MPI"
  option.entryPoint: "djl_python.tensorrt_llm"
  option.rolling_batch: "trtllm"
  option.tensor_parallel_degree: 8
  option.max_rolling_batch_size: 8
  option.output_formatter: "json"
  option.max_num_tokens: 8192
  option.dtype: "fp16"
  option.trust_remote_code: true
sagemaker:
  model:
    name: "mistral-7b-instruct-v0-2-tensorrt-llm"
    container: "containers/tensorrt-llm"
    env: 
      HUGGINGFACE_HUB_CACHE: "/tmp"
      TRANSFORMERS_CACHE: "/tmp"
  endpoint:
    name: "mistral-7b-instruct-v0-2-tensorrt-llm"
    instance_type: "ml.g5.48xlarge"
    initial_instance_count: 1
    variant_name: "test"
    model_data_download_timeout_secs: 1800
    container_startup_health_check_timeout_secs: 1200
test:
  module_name: "prompt_generator"
  module_dir: "modules/inst-semeval2017"
  prompt_generator: "PromptGenerator"
  params: { "do_sample": true, "max_new_tokens": 1024, "top_k": 50 }
  warmup_iters: 1
  max_iters: 10
  n_concurrent: 4
  output_dir: "output"
  locust_users: 24
  locust_workers: 4