huggingface:
  model: "cross-encoder/ms-marco-MiniLM-L-6-v2"
  revision: "b2cfda50a1a9fc7919e7444afbb52610d268af92"
  download: true
djl:
  engine: "Python"
  option.model_loading_timeout: 1800
  option.max_dynamic_batch_size: 16
  option.trust_remote_code: true
sagemaker:
  model:
    name: "ms-marco-minilm-l6v2-pytorch-neuronx"
    container:  "containers/pytorch-inf2"
    env:
      TOKENIZERS_PARALLELISM: "false"
  endpoint:
    name:  "ms-marco-minilm-l6v2-pytorch-neuronx"
    instance_type: "ml.inf2.xlarge"
    initial_instance_count: 1
    variant_name: "test"
    model_data_download_timeout_secs: 1800
    container_startup_health_check_timeout_secs: 1200
test:
  module_name: "reranker_pair"
  module_dir: "modules/inst-semeval2017"
  prompt_generator: "RerankerPair"
  task_name: "reranker"
  template: { "inputs": ""  }
  template_keys: ["inputs"]
  warmup_iters: 1
  max_iters: 10
  output_dir: "output"