huggingface:
  model: "deepseek-ai/DeepSeek-R1-Distill-Llama-8B"
  revision: "ebf7e8d03db3d86a442d22d30d499abb7ec27bea"
  download: true
djl:
  engine: "Python"
  option.entryPoint: "djl_python.transformers_neuronx"
  option.tensor_parallel_degree: 8
  option.amp: "f16"
  option.n_positions: 8192
  option.model_loading_timeout: 1800
  option.model_loader: "tnx"
  option.rolling_batch: "auto"
  option.rolling_batch_strategy: "continuous_batching"
  option.max_rolling_batch_size: 8
  option.output_formatter: "json"
  option.trust_remote_code: true
sagemaker:
  model:
    name: "deepseek-r1-distill-llama-8b-transformers-neuronx"
    container:  "containers/pytorch-inf2"
    env: 
      HUGGINGFACE_HUB_CACHE: "/tmp"
      TRANSFORMERS_CACHE: "/tmp"
  endpoint:
    name: "deepseek-r1-distill-llama-8b-transformers-neuronx"
    instance_type: "ml.inf2.48xlarge"
    initial_instance_count: 1
    variant_name: "test"
    model_data_download_timeout_secs: 1800
    container_startup_health_check_timeout_secs: 1200
    volume_size_gb: 200
test:
  module_name: "llama3_prompt_generator"
  module_dir: "modules/inst-semeval2017"
  prompt_generator: "PromptGenerator"
  params: { "do_sample": true, "max_new_tokens": 1024, "top_k": 50 }
  warmup_iters: 1
  max_iters: 10
  n_concurrent: 4
  output_dir: "output"
  locust_users: 4
  locust_workers: 1
